"""LP-52 stated financials models and MISMO core fields

Revision ID: 2680568f49c9
Revises: 8a153b35129b
Create Date: 2026-06-12 22:24:05.637812

Adds the stated-financials tables (stated_income_items, stated_employers,
stated_liabilities, stated_assets) and the MISMO import record (mismo_imports,
with the catch-all + raw-file reference), plus the nullable MISMO core fields on
borrowers / loan_files / properties. All new columns are nullable (manual
creation leaves them empty). New child tables FK to their parent with
ON DELETE CASCADE; mismo_imports.status is a VARCHAR + CHECK enum (ADR-037).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2680568f49c9"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "8a153b35129b"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mismo_imports",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("source_format", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "completed",
                "partial",
                "failed",
                name="mismoimportstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("parse_warnings", sa.JSON(), nullable=True),
        sa.Column("catch_all", sa.JSON(), nullable=True),
        sa.Column("raw_file_path", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_mismo_imports_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mismo_imports")),
    )
    op.create_index(
        op.f("ix_mismo_imports_loan_file_id"), "mismo_imports", ["loan_file_id"], unique=False
    )
    op.create_table(
        "stated_assets",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("asset_type", sa.String(length=64), nullable=True),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("holder_name", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_stated_assets_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stated_assets")),
    )
    op.create_index(
        op.f("ix_stated_assets_loan_file_id"), "stated_assets", ["loan_file_id"], unique=False
    )
    op.create_table(
        "stated_liabilities",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("liability_type", sa.String(length=64), nullable=True),
        sa.Column("monthly_payment", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("unpaid_balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("holder_name", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_stated_liabilities_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stated_liabilities")),
    )
    op.create_index(
        op.f("ix_stated_liabilities_loan_file_id"),
        "stated_liabilities",
        ["loan_file_id"],
        unique=False,
    )
    op.create_table(
        "stated_employers",
        sa.Column("borrower_id", sa.Uuid(), nullable=False),
        sa.Column("employer_name", sa.String(length=256), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["borrowers.id"],
            name=op.f("fk_stated_employers_borrower_id_borrowers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stated_employers")),
    )
    op.create_index(
        op.f("ix_stated_employers_borrower_id"), "stated_employers", ["borrower_id"], unique=False
    )
    op.create_table(
        "stated_income_items",
        sa.Column("borrower_id", sa.Uuid(), nullable=False),
        sa.Column("monthly_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("income_type", sa.String(length=64), nullable=True),
        sa.Column("employment_income", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["borrowers.id"],
            name=op.f("fk_stated_income_items_borrower_id_borrowers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stated_income_items")),
    )
    op.create_index(
        op.f("ix_stated_income_items_borrower_id"),
        "stated_income_items",
        ["borrower_id"],
        unique=False,
    )
    op.add_column("borrowers", sa.Column("dependent_count", sa.Integer(), nullable=True))
    op.add_column("borrowers", sa.Column("citizenship", sa.String(length=64), nullable=True))
    op.add_column("borrowers", sa.Column("declarations", sa.JSON(), nullable=True))
    op.add_column(
        "loan_files", sa.Column("note_amount", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "loan_files",
        sa.Column("note_rate_percent", sa.Numeric(precision=7, scale=4), nullable=True),
    )
    op.add_column("loan_files", sa.Column("lien_priority", sa.String(length=64), nullable=True))
    op.add_column("loan_files", sa.Column("amortization_type", sa.String(length=64), nullable=True))
    op.add_column("loan_files", sa.Column("amortization_months", sa.Integer(), nullable=True))
    op.add_column("loan_files", sa.Column("application_received_date", sa.Date(), nullable=True))
    op.add_column(
        "properties",
        sa.Column("valuation_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column("properties", sa.Column("attachment_type", sa.String(length=64), nullable=True))
    op.add_column(
        "properties", sa.Column("construction_method", sa.String(length=64), nullable=True)
    )
    op.add_column("properties", sa.Column("financed_unit_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "financed_unit_count")
    op.drop_column("properties", "construction_method")
    op.drop_column("properties", "attachment_type")
    op.drop_column("properties", "valuation_amount")
    op.drop_column("loan_files", "application_received_date")
    op.drop_column("loan_files", "amortization_months")
    op.drop_column("loan_files", "amortization_type")
    op.drop_column("loan_files", "lien_priority")
    op.drop_column("loan_files", "note_rate_percent")
    op.drop_column("loan_files", "note_amount")
    op.drop_column("borrowers", "declarations")
    op.drop_column("borrowers", "citizenship")
    op.drop_column("borrowers", "dependent_count")
    op.drop_index(op.f("ix_stated_income_items_borrower_id"), table_name="stated_income_items")
    op.drop_table("stated_income_items")
    op.drop_index(op.f("ix_stated_employers_borrower_id"), table_name="stated_employers")
    op.drop_table("stated_employers")
    op.drop_index(op.f("ix_stated_liabilities_loan_file_id"), table_name="stated_liabilities")
    op.drop_table("stated_liabilities")
    op.drop_index(op.f("ix_stated_assets_loan_file_id"), table_name="stated_assets")
    op.drop_table("stated_assets")
    op.drop_index(op.f("ix_mismo_imports_loan_file_id"), table_name="mismo_imports")
    op.drop_table("mismo_imports")
    # ### end Alembic commands ###
