"""create_documents

Revision ID: a513e98e399f
Revises: 82c2b1989cce
Create Date: 2026-06-11 08:50:48.385063

Creates the ``documents`` table (LP-15) — one row per uploaded file attached to
a loan file. The row holds **metadata and a storage path**, never the bytes
(ADR-055): the binary lives in the storage backend (LP-35).

It is an owned child of the loan file (FK ``loan_file_id``, ``ondelete=CASCADE``,
indexed) with no ``company_id`` — company scoping is transitive through the file
(ADR-052). ``uploaded_by_user_id`` is a **nullable** FK to users with
``ondelete=RESTRICT`` (null for borrower-inbox / MISMO imports, which have no
user actor; RESTRICT keeps an uploader from being hard-deleted out from under
their documents, consistent with the soft-delete approach — ADR-056).

Three columns are VARCHAR + CHECK enums (ADR-037): ``category`` (the eight
categories), ``status`` (the processing lifecycle, ADR-054), and
``upload_source`` (provenance). ``document_type`` is a **plain indexed string**,
not an enum — the ~100-type set is finalized in Phase 2 and governed at the app
layer (ADR-053). ``classification_confidence`` is a float; ``file_size_bytes`` an
integer; ``processing_error`` free text. Indexed on ``loan_file_id``,
``document_type``, ``status``, and ``uploaded_by_user_id``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a513e98e399f"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "82c2b1989cce"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=256), nullable=False),
        sa.Column("mime_type", sa.String(length=256), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "assets",
                "borrower_info",
                "credit",
                "disclosures",
                "income_employment",
                "property",
                "misc",
                "custom",
                name="documentcategory",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "classifying",
                "classified",
                "extracting",
                "completed",
                "failed",
                "needs_review",
                name="documentstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "upload_source",
            sa.Enum(
                "user_upload",
                "borrower_inbox",
                "mismo_import",
                name="uploadsource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_documents_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False
    )
    op.create_index(op.f("ix_documents_loan_file_id"), "documents", ["loan_file_id"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        op.f("ix_documents_uploaded_by_user_id"),
        "documents",
        ["uploaded_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_uploaded_by_user_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_loan_file_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
