"""create_findings

Revision ID: 2b2266d15127
Revises: aa3e537ea73f
Create Date: 2026-06-11 09:32:27.188186

Creates the ``findings`` table (LP-17) — individual verification results
(red/yellow/green flags) against a loan file. A finding is an owned child of the
loan file (FK ``loan_file_id``, ``ondelete=CASCADE``, indexed) with no
``company_id`` — scoped transitively through the file (ADR-052). Its resolution
state persists across verification runs because it belongs to the durable loan
file, not to a run (ADR-061).

``status``, ``category``, and ``resolution_status`` are VARCHAR + CHECK enums
(ADR-037). ``rule_id`` is a plain indexed string (a dotted namespace, governed at
the app layer — ADR-062), not an enum.

Foreign keys: ``source_document_id`` and ``resolved_by_user_id`` are nullable
with ``ondelete=SET NULL`` (the finding survives if the document or resolving
user is removed). ``verification_id`` is a **nullable UUID column with NO foreign
key constraint** — the ``verifications`` table does not exist until LP-18, which
adds the constraint (ADR-063); it is indexed now. Indexed columns:
``loan_file_id``, ``verification_id``, ``source_document_id``, ``rule_id``,
``status``, ``category``, ``resolution_status``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b2266d15127"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "aa3e537ea73f"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        # Nullable UUID with NO FK constraint yet — added in LP-18 (ADR-063).
        sa.Column("verification_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("rule_id", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "red",
                "yellow",
                "green",
                name="findingstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "income",
                "assets",
                "credit",
                "property",
                "documentation",
                "cross_source",
                "regulatory",
                name="findingcategory",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "resolution_status",
            sa.Enum(
                "open",
                "resolved",
                "accepted_risk",
                "waived",
                name="findingresolutionstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_findings_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_findings_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_findings_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(op.f("ix_findings_category"), "findings", ["category"], unique=False)
    op.create_index(op.f("ix_findings_loan_file_id"), "findings", ["loan_file_id"], unique=False)
    op.create_index(
        op.f("ix_findings_resolution_status"), "findings", ["resolution_status"], unique=False
    )
    op.create_index(op.f("ix_findings_rule_id"), "findings", ["rule_id"], unique=False)
    op.create_index(
        op.f("ix_findings_source_document_id"), "findings", ["source_document_id"], unique=False
    )
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_index(
        op.f("ix_findings_verification_id"), "findings", ["verification_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_findings_verification_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_source_document_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_rule_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_resolution_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_loan_file_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_category"), table_name="findings")
    op.drop_table("findings")
    # ### end Alembic commands ###
