"""create_loan_files

Revision ID: 97f1d55c56ee
Revises: f9ed4a63a97e
Create Date: 2026-06-10 23:00:51.241650

Creates the ``loan_files`` table (LP-13) — the central entity of the system,
implementing the three-identifier design (ADR-036): a UUID primary key
(internal), a globally-unique non-sequential ``display_id`` (``LF-XXXX``, human
reference, ADR-048), and a globally-unique cryptographic ``inbox_token`` (the
borrower email capability). Both identifiers get unique indexes. ``company_id``
is required and ``lender_id`` nullable, both RESTRICT foreign keys (ADR-044).
``status`` (lifecycle, ADR-049), ``loan_program``, and ``loan_purpose`` are
VARCHAR + CHECK enums (ADR-037); ``loan_amount`` is ``NUMERIC(14,2)`` (ADR-038).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97f1d55c56ee"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "f9ed4a63a97e"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loan_files",
        sa.Column("display_id", sa.String(length=64), nullable=False),
        sa.Column("inbox_token", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("lender_id", sa.Uuid(), nullable=True),
        sa.Column(
            "loan_program",
            sa.Enum(
                "conventional",
                "fha",
                name="loanprogram",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "loan_purpose",
            sa.Enum(
                "purchase",
                "refinance",
                name="loanpurpose",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("loan_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_processing",
                "ready_to_submit",
                "submitted",
                "in_conditions",
                "clear_to_close",
                "closed",
                "withdrawn",
                name="loanfilestatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("loan_officer_name", sa.String(length=256), nullable=True),
        sa.Column("loan_officer_email", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_loan_files_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lender_id"],
            ["lenders.id"],
            name=op.f("fk_loan_files_lender_id_lenders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_files")),
    )
    op.create_index(op.f("ix_loan_files_company_id"), "loan_files", ["company_id"], unique=False)
    op.create_index(op.f("ix_loan_files_display_id"), "loan_files", ["display_id"], unique=True)
    op.create_index(op.f("ix_loan_files_inbox_token"), "loan_files", ["inbox_token"], unique=True)
    op.create_index(op.f("ix_loan_files_lender_id"), "loan_files", ["lender_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loan_files_lender_id"), table_name="loan_files")
    op.drop_index(op.f("ix_loan_files_inbox_token"), table_name="loan_files")
    op.drop_index(op.f("ix_loan_files_display_id"), table_name="loan_files")
    op.drop_index(op.f("ix_loan_files_company_id"), table_name="loan_files")
    op.drop_table("loan_files")
    # ### end Alembic commands ###
