"""create_verifications_and_link_findings

Revision ID: 69fb46c9cc5b
Revises: 2b2266d15127
Create Date: 2026-06-11 09:49:13.452141

Creates the ``verifications`` table (LP-18) — one row per execution of the
verification engine against a loan file — and **wires the deferred FK** on
``findings.verification_id`` now that the target table exists (ADR-066, deferred
from LP-17 / ADR-063). This migration therefore touches **two** tables.

``verifications`` is an owned child of the loan file (FK ``loan_file_id``,
``ondelete=CASCADE``, indexed) with no ``company_id`` — scoped transitively
through the file (ADR-052). ``status`` and ``trigger`` are VARCHAR + CHECK enums
(ADR-037); ``red_count`` / ``yellow_count`` / ``green_count`` are denormalized
summary counts (ADR-065).

The findings FK is ``ondelete=SET NULL`` — **not** CASCADE — because a finding
belongs to the loan file, not to a run: deleting a run preserves its findings and
only nulls their ``verification_id`` (ADR-064). The downgrade drops that FK
before dropping the table.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69fb46c9cc5b"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "2b2266d15127"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verifications",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="verificationstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum(
                "manual",
                "automatic",
                name="verificationtrigger",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("red_count", sa.Integer(), nullable=False),
        sa.Column("yellow_count", sa.Integer(), nullable=False),
        sa.Column("green_count", sa.Integer(), nullable=False),
        sa.Column("total_tokens_used", sa.Integer(), nullable=True),
        sa.Column("total_cost_estimate", sa.Float(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_verifications_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verifications")),
    )
    op.create_index(
        op.f("ix_verifications_loan_file_id"), "verifications", ["loan_file_id"], unique=False
    )
    op.create_index(op.f("ix_verifications_status"), "verifications", ["status"], unique=False)
    # Wire the deferred FK on findings.verification_id (LP-17 left it bare).
    # SET NULL: deleting a run preserves its findings (ADR-064).
    op.create_foreign_key(
        op.f("fk_findings_verification_id_verifications"),
        "findings",
        "verifications",
        ["verification_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_findings_verification_id_verifications"), "findings", type_="foreignkey"
    )
    op.drop_index(op.f("ix_verifications_status"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_loan_file_id"), table_name="verifications")
    op.drop_table("verifications")
    # ### end Alembic commands ###
