"""LP-643 — dti_custom_lines: a DTI row a processor added, that the engine did not produce.

Hand-written rather than autogenerated. `--autogenerate` against this database also picked up three
pre-existing drifts unrelated to this change (a `validation_verdicts.title` length, a
`verifications.cross_check_count` server default, a removed `verifications.fact_snapshot`), and a
migration that quietly carries someone else's drift is worse than one that does one thing.

NO UNIQUE CONSTRAINT, deliberately — the opposite of `dti_overrides`. An override is one-per-field
because a field has one value; two custom lines with the same label are two real additions (a
borrower can have two side jobs), and de-duplicating them would silently drop a processor's second
entry.

Revision ID: e4a1c9f3b028
Revises: c8b1e47da920
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e4a1c9f3b028"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "c8b1e47da920"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "dti_custom_lines",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column(
            "loan_file_id",
            sa.UUID(),
            sa.ForeignKey("loan_files.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("section", sa.String(length=256), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_dti_custom_lines_loan_file",
        "dti_custom_lines",
        ["loan_file_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_dti_custom_lines_loan_file", table_name="dti_custom_lines")
    op.drop_table("dti_custom_lines")
