"""LP-842 — a need remembers what the document has to establish.

HAND-WRITTEN, NOT AUTOGENERATED. `--autogenerate` against this dev database proposed dropping five
`borrowers` address columns and rewriting `communication_evidence`: the local database is behind the
models, and autogenerate reads that drift as intent. A generated migration is only as good as the
database it was generated against, and this one would have deleted borrower addresses in every
environment it reached.

Revision ID: f4a1c9d2e7b3
Revises: c7d2e94f1a35
Create Date: 2026-09-11
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f4a1c9d2e7b3"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "c7d2e94f1a35"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_GRANT = """
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mbai_readonly') THEN
            EXECUTE 'GRANT SELECT ON readonly.needs_items TO mbai_readonly';
        END IF;
    END $$;
"""


def upgrade() -> None:
    """Add the outward-safe ask a request carries, and expose it scrubbed.

    NULLABLE with no backfill, and that is the correct history rather than a shortcut: a need created
    before this column existed was requested without an ask, and inventing one now would put words
    into an email a processor already sent.

    SCRUBBED IN THE VIEW, LIKE EVERY OTHER FREE-TEXT COLUMN ON THIS TABLE. `title`, `description`,
    `notes`, `reasoning` and `reason` all go through `readonly.scrub`. This one is rule-spec text and
    carries no borrower data, so scrubbing changes nothing anybody would read — which is the argument
    for doing it rather than against. A raw column among scrubbed siblings is an asymmetry the next
    author has to rediscover, and deciding per column that this one is fine is how that starts.

    THE VIEW IS REBUILT, not altered: a view's column list is fixed at creation, so adding the column
    to the table does not add it to the view. `test_no_model_column_drifts` is what says so out loud.
    """
    op.add_column("needs_items", sa.Column("outbound_ask", sa.Text(), nullable=True))
    op.execute("DROP VIEW IF EXISTS readonly.needs_items")
    op.execute(
        """
        CREATE VIEW readonly.needs_items AS
        SELECT id, loan_file_id, borrower_id,
               readonly.scrub(title) AS title,
               readonly.scrub(description) AS description,
               category, needs_type, origin, priority, status,
               satisfied_by_document_id, satisfied_at, requested_at,
               readonly.scrub(notes) AS notes,
               disposition,
               readonly.scrub(reasoning) AS reasoning,
               readonly.scrub(explanation) AS explanation,
               readonly.scrub(reason) AS reason,
               readonly.scrub(outbound_ask) AS outbound_ask,
               source_finding_id,
               readonly.scrub_json(source_facts) AS source_facts,
               duplicate_reviewed, duplicate_of_id,
               covered_by_document_id,
               readonly.scrub(coverage_note) AS coverage_note,
               coverage_reviewed,
               created_at, updated_at, deleted_at
        FROM public.needs_items
        """
    )
    op.execute(_GRANT)


def downgrade() -> None:
    """Put the view back to C7's shape before the column goes, or the DROP fails on the dependency."""
    op.execute("DROP VIEW IF EXISTS readonly.needs_items")
    op.execute(
        """
        CREATE VIEW readonly.needs_items AS
        SELECT id, loan_file_id, borrower_id,
               readonly.scrub(title) AS title,
               readonly.scrub(description) AS description,
               category, needs_type, origin, priority, status,
               satisfied_by_document_id, satisfied_at, requested_at,
               readonly.scrub(notes) AS notes,
               disposition,
               readonly.scrub(reasoning) AS reasoning,
               readonly.scrub(explanation) AS explanation,
               readonly.scrub(reason) AS reason,
               source_finding_id,
               readonly.scrub_json(source_facts) AS source_facts,
               duplicate_reviewed, duplicate_of_id,
               covered_by_document_id,
               readonly.scrub(coverage_note) AS coverage_note,
               coverage_reviewed,
               created_at, updated_at, deleted_at
        FROM public.needs_items
        """
    )
    op.execute(_GRANT)
    op.drop_column("needs_items", "outbound_ask")
