"""create_communications_and_activity_logs

Revision ID: bf89fba42bdc
Revises: 4db01a03523e
Create Date: 2026-06-11 10:22:40.935971

Creates two event-record tables (LP-20), both owned children of the loan file
(FK ``loan_file_id``, ``ondelete=CASCADE``, indexed) with no ``company_id`` —
scoped transitively through the file (ADR-052):

  * ``communications`` — messages in/out of a file. ``direction``, ``channel``
    (email only in V1, ADR-072), and ``status`` are VARCHAR + CHECK enums
    (ADR-037). ``needs_item_id`` and ``initiated_by_user_id`` are nullable FKs
    with ``ondelete=SET NULL`` (the message survives if the need/user is
    removed). Indexed on ``direction``, ``status``, ``needs_item_id``.

  * ``activity_logs`` — the file's audit trail (ADR-070/071). ``activity_type``
    is a VARCHAR + CHECK enum; ``actor_user_id`` is a nullable FK
    (``ondelete=SET NULL``, null = system); ``detail`` is JSON. Indexed on
    ``activity_type``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf89fba42bdc"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "4db01a03523e"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "file_created",
                "status_changed",
                "document_uploaded",
                "document_processed",
                "finding_resolved",
                "verification_run",
                "needs_item_created",
                "needs_item_satisfied",
                "communication_sent",
                "communication_received",
                "note_added",
                name="activitytype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.String(length=256), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_activity_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_activity_logs_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_logs")),
    )
    op.create_index(
        op.f("ix_activity_logs_activity_type"), "activity_logs", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_loan_file_id"), "activity_logs", ["loan_file_id"], unique=False
    )
    op.create_table(
        "communications",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="communicationdirection",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                name="communicationchannel",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "sent",
                "delivered",
                "failed",
                "received",
                name="communicationstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sender", sa.String(length=256), nullable=True),
        sa.Column("recipient", sa.String(length=256), nullable=True),
        sa.Column("subject", sa.String(length=256), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("needs_item_id", sa.Uuid(), nullable=True),
        sa.Column("initiated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("external_message_id", sa.String(length=256), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"],
            ["users.id"],
            name=op.f("fk_communications_initiated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_communications_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["needs_item_id"],
            ["needs_items.id"],
            name=op.f("fk_communications_needs_item_id_needs_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communications")),
    )
    op.create_index(
        op.f("ix_communications_direction"), "communications", ["direction"], unique=False
    )
    op.create_index(
        op.f("ix_communications_loan_file_id"), "communications", ["loan_file_id"], unique=False
    )
    op.create_index(
        op.f("ix_communications_needs_item_id"), "communications", ["needs_item_id"], unique=False
    )
    op.create_index(op.f("ix_communications_status"), "communications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_communications_status"), table_name="communications")
    op.drop_index(op.f("ix_communications_needs_item_id"), table_name="communications")
    op.drop_index(op.f("ix_communications_loan_file_id"), table_name="communications")
    op.drop_index(op.f("ix_communications_direction"), table_name="communications")
    op.drop_table("communications")
    op.drop_index(op.f("ix_activity_logs_loan_file_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_activity_type"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
