"""LP-635 persist a run's enqueued time limit

Adds ``verifications.time_limit_seconds`` — the hard limit the run was ENQUEUED with.

The stuck-run watchdog runs on READ, potentially hours after the run started, and derived its bound
from the file's CURRENT document count. Those are not the same number: soft-delete documents during a
long run and the derived bound shrinks below the one the running task is actually holding, so the
watchdog fails a healthy run and tells the processor it "timed out". Persisting what the run was
given makes the watchdog ask about that run rather than about the file as it looks now.

Nullable, with readers falling back to deriving the bound, so runs that predate this column behave
exactly as they did before.

WRITTEN BY HAND, NOT AUTOGENERATED. `alembic revision --autogenerate` against a drifted local
database proposed dropping `finding_prose`, the documents FTS index, five borrower address columns
and `properties.county` — none of which has anything to do with this change, and all of which would
have been destructive on an environment where those objects are live. Only the column below belongs
to LP-635.

Revision ID: ac1e2bddc9d1
Revises: b7d34e9a1c22
Create Date: 2026-08-30 23:03:52.777564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac1e2bddc9d1"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "b7d34e9a1c22"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the column and EXPOSE it in the readonly view.

    Exposed rather than excluded. It is an integer count of seconds with no identifier in it, and it
    answers the question this whole ticket turned on — "was this run given the budget its size
    earns?" — which was previously answerable only by reasoning from CloudWatch about a constant.

    THE SQL IS INLINE IN EACH FUNCTION, NOT HOISTED INTO MODULE CONSTANTS, and that is load-bearing
    rather than style. `tests/test_readonly_query.py::_later_view_redefinitions` finds the live view
    by reading only the text ahead of the rollback function, so a rollback definition parked in a
    module-level constant sits ABOVE that cut, wins the last-one-wins assignment, and is read as the
    live view. The first cut of this migration did exactly that, and the drift guard reported a
    column it had just exposed as unexposed. That guard's own comment names this as the failure it
    exists to prevent; hoisting reintroduces it from a direction the cut cannot see.

    Two consequences worth knowing before editing this file: the scanner is TEXT-based, so prose here
    that spells out its split marker truncates the very SQL below it (that also happened), and a
    future migration that hoists its view SQL will silently hand the guard the wrong definition.
    """
    op.add_column(
        "verifications",
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
    )
    op.execute(
        """
        CREATE OR REPLACE VIEW readonly.verifications AS
        SELECT id, loan_file_id, status, trigger, started_at, completed_at,
               red_count, yellow_count, green_count,
               total_tokens_used, total_cost_estimate, error_detail, input_fingerprint,
               created_at, updated_at, deleted_at,
               cross_check_count, time_limit_seconds
        FROM public.verifications
        """
    )


def downgrade() -> None:
    """The view SELECTs the column, so it must be dropped first: CREATE OR REPLACE cannot remove a
    column from an existing view."""
    op.execute("DROP VIEW IF EXISTS readonly.verifications CASCADE")
    op.drop_column("verifications", "time_limit_seconds")
    op.execute(
        """
        CREATE VIEW readonly.verifications AS
        SELECT id, loan_file_id, status, trigger, started_at, completed_at,
               red_count, yellow_count, green_count,
               total_tokens_used, total_cost_estimate, error_detail, input_fingerprint,
               created_at, updated_at, deleted_at,
               cross_check_count
        FROM public.verifications
        """
    )
    # CASCADE + recreate loses the grant, so it is reinstated exactly as the view's own migration
    # does — guarded, because the role does not exist in every environment.
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mbai_readonly') THEN
                GRANT SELECT ON readonly.verifications TO mbai_readonly;
            END IF;
        END $$;
    """)
