"""create_extractions

Revision ID: aa3e537ea73f
Revises: a513e98e399f
Create Date: 2026-06-11 09:11:04.439035

Creates the ``extractions`` table (LP-16) — versioned structured data extracted
from a document by AI. The extracted fields live in the ``extracted_data`` JSON
column; their structure is governed by Pydantic schemas at the application layer
(Phase 2), not by the database (ADR-057).

Extractions are an owned child of the document (FK ``document_id``,
``ondelete=CASCADE``, indexed) with no ``company_id`` — scoped transitively
through ``document -> loan_file`` (ADR-052). ``extraction_status`` is a VARCHAR +
CHECK enum (ADR-037).

Versioning (ADR-058): ``version`` is sequential per document and ``is_current``
marks the active version. A **partial unique index**
``uq_extractions_document_id_current`` — ``UNIQUE (document_id) WHERE
is_current`` — guarantees exactly one current extraction per document while
allowing any number of historical (``is_current = false``) versions. Autogenerate
emitted the ``WHERE`` clause via ``postgresql_where``; verified in psql.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa3e537ea73f"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "a513e98e399f"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extractions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("extracted_data", sa.JSON(), nullable=False),
        sa.Column(
            "extraction_status",
            sa.Enum(
                "succeeded",
                "failed",
                "partial",
                name="extractionstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("model_used", sa.String(length=64), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("cost_estimate", sa.Float(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_extractions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extractions")),
    )
    op.create_index(
        op.f("ix_extractions_document_id"), "extractions", ["document_id"], unique=False
    )
    # Partial unique index: one current extraction per document (ADR-058).
    op.create_index(
        "uq_extractions_document_id_current",
        "extractions",
        ["document_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_extractions_document_id_current",
        table_name="extractions",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(op.f("ix_extractions_document_id"), table_name="extractions")
    op.drop_table("extractions")
    # ### end Alembic commands ###
