"""create_needs_items

Revision ID: 4db01a03523e
Revises: 69fb46c9cc5b
Create Date: 2026-06-11 10:03:48.363111

Creates the ``needs_items`` table (LP-19) — the loan file's needs-list checklist
of outstanding requirements. An owned child of the loan file (FK ``loan_file_id``,
``ondelete=CASCADE``, indexed) with no ``company_id`` — scoped transitively
through the file (ADR-052).

Four columns are VARCHAR + CHECK enums (ADR-037): ``category`` (the reused
``DocumentCategory`` set, ADR-068), ``origin``, ``priority``, and ``status``.
``needs_type`` is a plain indexed string (a flexible app-layer type, ADR-053),
not an enum.

The ``borrower_id`` and ``satisfied_by_document_id`` FKs are nullable with
``ondelete=SET NULL`` — the durable needs item survives if the borrower or
satisfying document is removed (ADR-069). Indexed columns: ``loan_file_id``,
``needs_type``, ``borrower_id``, ``priority``, ``status``,
``satisfied_by_document_id``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4db01a03523e"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "69fb46c9cc5b"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "needs_items",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "assets",
                "borrower_info",
                "credit",
                "disclosures",
                "income_employment",
                "property",
                "misc",
                "custom",
                name="documentcategory",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("needs_type", sa.String(length=64), nullable=True),
        sa.Column("borrower_id", sa.Uuid(), nullable=True),
        sa.Column(
            "origin",
            sa.Enum(
                "manual",
                "finding",
                "condition",
                "template",
                name="needsitemorigin",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "blocking",
                "standard",
                "low",
                name="needsitempriority",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "outstanding",
                "requested",
                "received",
                "waived",
                name="needsitemstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("satisfied_by_document_id", sa.Uuid(), nullable=True),
        sa.Column("satisfied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["borrowers.id"],
            name=op.f("fk_needs_items_borrower_id_borrowers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_needs_items_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["satisfied_by_document_id"],
            ["documents.id"],
            name=op.f("fk_needs_items_satisfied_by_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_needs_items")),
    )
    op.create_index(
        op.f("ix_needs_items_borrower_id"), "needs_items", ["borrower_id"], unique=False
    )
    op.create_index(
        op.f("ix_needs_items_loan_file_id"), "needs_items", ["loan_file_id"], unique=False
    )
    op.create_index(op.f("ix_needs_items_needs_type"), "needs_items", ["needs_type"], unique=False)
    op.create_index(op.f("ix_needs_items_priority"), "needs_items", ["priority"], unique=False)
    op.create_index(
        op.f("ix_needs_items_satisfied_by_document_id"),
        "needs_items",
        ["satisfied_by_document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_needs_items_status"), "needs_items", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_needs_items_status"), table_name="needs_items")
    op.drop_index(op.f("ix_needs_items_satisfied_by_document_id"), table_name="needs_items")
    op.drop_index(op.f("ix_needs_items_priority"), table_name="needs_items")
    op.drop_index(op.f("ix_needs_items_needs_type"), table_name="needs_items")
    op.drop_index(op.f("ix_needs_items_loan_file_id"), table_name="needs_items")
    op.drop_index(op.f("ix_needs_items_borrower_id"), table_name="needs_items")
    op.drop_table("needs_items")
    # ### end Alembic commands ###
