"""create borrowers and properties

Revision ID: 82c2b1989cce
Revises: 97f1d55c56ee
Create Date: 2026-06-10 23:42:17.755804

Creates the ``borrowers`` and ``properties`` tables (LP-14), the people and real
estate attached to a loan file. Both are owned by the file via a
``loan_file_id`` foreign key with ``ondelete=CASCADE`` (a hard delete of a file
removes them; normal flow soft-deletes). Neither carries a ``company_id`` —
company scoping is transitive through the loan file (ADR-052).

``borrowers`` is a one-to-many (primary borrower + co-borrowers), indexed on
``loan_file_id``. The ``ssn`` column is plain ``TEXT`` at the database level: the
application encrypts it with Fernet before write and decrypts after read
(ADR-051, see :class:`app.models.encrypted_types.EncryptedString`), so the raw
column holds only ciphertext. ``marital_status`` is a VARCHAR + CHECK enum
(ADR-037). Date of birth is stored unencrypted in V1 (documented in the model).

``properties`` is a one-to-one: a UNIQUE constraint on ``loan_file_id`` enforces
at most one subject property per file. ``property_type`` and ``occupancy_type``
are VARCHAR + CHECK enums; ``estimated_value`` and ``purchase_price`` are
``NUMERIC(14,2)`` money columns (ADR-038).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82c2b1989cce"  # pragma: allowlist secret  (Alembic revision id, not a secret)
down_revision: str | Sequence[str] | None = "97f1d55c56ee"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borrowers",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("middle_name", sa.String(length=64), nullable=True),
        # SSN stored as TEXT ciphertext — encrypted/decrypted in the app
        # (Fernet, ADR-051). The database never sees the plaintext.
        sa.Column("ssn", sa.Text(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column(
            "marital_status",
            sa.Enum(
                "married",
                "unmarried",
                "separated",
                name="maritalstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("borrower_position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_borrowers_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrowers")),
    )
    op.create_index(op.f("ix_borrowers_loan_file_id"), "borrowers", ["loan_file_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column("loan_file_id", sa.Uuid(), nullable=False),
        sa.Column("address_line", sa.String(length=256), nullable=True),
        sa.Column("address_line_2", sa.String(length=256), nullable=True),
        sa.Column("city", sa.String(length=256), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("postal_code", sa.String(length=16), nullable=True),
        sa.Column(
            "property_type",
            sa.Enum(
                "single_family",
                "condo",
                "townhouse",
                "multi_family",
                "manufactured",
                "other",
                name="propertytype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "occupancy_type",
            sa.Enum(
                "primary_residence",
                "second_home",
                "investment",
                name="occupancytype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("estimated_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_file_id"],
            ["loan_files.id"],
            name=op.f("fk_properties_loan_file_id_loan_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
        # One subject property per file in V1 (the one-to-one).
        sa.UniqueConstraint("loan_file_id", name=op.f("uq_properties_loan_file_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("properties")
    op.drop_index(op.f("ix_borrowers_loan_file_id"), table_name="borrowers")
    op.drop_table("borrowers")
    # ### end Alembic commands ###
